version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: 'Europe/Stockholm'
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: 'Europe/Stockholm'
