name: Dependabot CD
on: pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - name: run test
      run: npm test
    - name: run typescript build
      run: npm run build

  approve_pr:
    if: github.actor == 'dependabot[bot]'
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: review
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.BUILD_TOKEN }}
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number,
              event: 'APPROVE'
            });
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: '@dependabot merge'
            });
